# Generated by Django 4.2.2 on 2023-10-02 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_room_code_room_guest_can_pause_room_host_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='created_at',
            new_name='createdAt',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='guest_can_pause',
            new_name='guestCanPause',
        ),
        migrations.RenameField(
            model_name='room',
            old_name='votes_to_skip',
            new_name='votesToSkip',
        ),
    ]
