# Generated by Django 4.2.2 on 2023-10-22 15:38

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_created_at_room_createdat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='code',
            field=models.CharField(default=api.models.Generate_unique_code, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='createdAt',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='host',
            field=models.CharField(default='', max_length=20),
        ),
    ]
